project:
  type: website
  output-dir: docs

website:
  title: "My phenomenal first website!"
  navbar:
    right: 
      - text: "About Me"
        href: about.html
      - text: "Data Viz"
        menu: 
         - text: "Simpsons"
           href: simpsons.html
         - text: "Valentine's Day"
           href: valentine.html
        - text: "The Office Lines"
           href: theoffice.html


