project:
  type: website
  output-dir: docs

website:
  title: "My phenomenal first website!"
  navbar:
    right: 
      - text: "About Me"
        href: about.html
      - text: "Data Viz"
        menu: 
         - text: "Simpsons"
           href: simpsons.html
         - text: "Valentine's Day"
           href: valentine.html
         - text: "The Office"
           href: theofice.html
         - text: "Mini-Proejct 3"
           href: project3.html
         - text: "Proejct 4"
           href: project4.html  
         - text: "Proejct 5"
           href: project5.html        


